<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Promotion', 'doctrine');

/**
 * BasePromotion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $promotion_id
 * @property float $price
 * @property float $discount
 * @property integer $is_recommend
 * @property integer $is_active
 * @property string $comment
 * @property integer $book_id
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * @property Books $Books
 * 
 * @method integer   getPromotionId()  Returns the current record's "promotion_id" value
 * @method float     getPrice()        Returns the current record's "price" value
 * @method float     getDiscount()     Returns the current record's "discount" value
 * @method integer   getIsRecommend()  Returns the current record's "is_recommend" value
 * @method integer   getIsActive()     Returns the current record's "is_active" value
 * @method string    getComment()      Returns the current record's "comment" value
 * @method integer   getBookId()       Returns the current record's "book_id" value
 * @method timestamp getCreatedAt()    Returns the current record's "created_at" value
 * @method timestamp getUpdatedAt()    Returns the current record's "updated_at" value
 * @method Books     getBooks()        Returns the current record's "Books" value
 * @method Promotion setPromotionId()  Sets the current record's "promotion_id" value
 * @method Promotion setPrice()        Sets the current record's "price" value
 * @method Promotion setDiscount()     Sets the current record's "discount" value
 * @method Promotion setIsRecommend()  Sets the current record's "is_recommend" value
 * @method Promotion setIsActive()     Sets the current record's "is_active" value
 * @method Promotion setComment()      Sets the current record's "comment" value
 * @method Promotion setBookId()       Sets the current record's "book_id" value
 * @method Promotion setCreatedAt()    Sets the current record's "created_at" value
 * @method Promotion setUpdatedAt()    Sets the current record's "updated_at" value
 * @method Promotion setBooks()        Sets the current record's "Books" value
 * 
 * @package    BookCity
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePromotion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('promotion');
        $this->hasColumn('promotion_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('price', 'float', 18, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 18,
             ));
        $this->hasColumn('discount', 'float', 18, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 18,
             ));
        $this->hasColumn('is_recommend', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('is_active', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('comment', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('book_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Books', array(
             'local' => 'book_id',
             'foreign' => 'book_id'));
    }
}