<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Advertisment', 'doctrine');

/**
 * BaseAdvertisment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $advertisment_id
 * @property string $name
 * @property string $url
 * @property string $img_url
 * @property string $comment
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * @property Doctrine_Collection $ClientBooksAdvertisment
 * 
 * @method integer             getAdvertismentId()          Returns the current record's "advertisment_id" value
 * @method string              getName()                    Returns the current record's "name" value
 * @method string              getUrl()                     Returns the current record's "url" value
 * @method string              getImgUrl()                  Returns the current record's "img_url" value
 * @method string              getComment()                 Returns the current record's "comment" value
 * @method timestamp           getCreatedAt()               Returns the current record's "created_at" value
 * @method timestamp           getUpdatedAt()               Returns the current record's "updated_at" value
 * @method Doctrine_Collection getClientBooksAdvertisment() Returns the current record's "ClientBooksAdvertisment" collection
 * @method Advertisment        setAdvertismentId()          Sets the current record's "advertisment_id" value
 * @method Advertisment        setName()                    Sets the current record's "name" value
 * @method Advertisment        setUrl()                     Sets the current record's "url" value
 * @method Advertisment        setImgUrl()                  Sets the current record's "img_url" value
 * @method Advertisment        setComment()                 Sets the current record's "comment" value
 * @method Advertisment        setCreatedAt()               Sets the current record's "created_at" value
 * @method Advertisment        setUpdatedAt()               Sets the current record's "updated_at" value
 * @method Advertisment        setClientBooksAdvertisment() Sets the current record's "ClientBooksAdvertisment" collection
 * 
 * @package    BookCity
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAdvertisment extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('advertisment');
        $this->hasColumn('advertisment_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('name', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('url', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('img_url', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('comment', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('ClientBooksAdvertisment', array(
             'local' => 'advertisment_id',
             'foreign' => 'advertisment_id'));
    }
}