<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Ordered', 'doctrine');

/**
 * BaseOrdered
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $orders_id
 * @property string $guy_addr
 * @property string $guy_phone
 * @property integer $is_paied
 * @property string $guy_payway
 * @property string $pay_status
 * @property integer $is_delivery
 * @property integer $is_receipt
 * @property float $post_money
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * @property Doctrine_Collection $ClientBooksAdvertisment
 * @property Doctrine_Collection $OrderDetail
 * 
 * @method integer             getOrdersId()                Returns the current record's "orders_id" value
 * @method string              getGuyAddr()                 Returns the current record's "guy_addr" value
 * @method string              getGuyPhone()                Returns the current record's "guy_phone" value
 * @method integer             getIsPaied()                 Returns the current record's "is_paied" value
 * @method string              getGuyPayway()               Returns the current record's "guy_payway" value
 * @method string              getPayStatus()               Returns the current record's "pay_status" value
 * @method integer             getIsDelivery()              Returns the current record's "is_delivery" value
 * @method integer             getIsReceipt()               Returns the current record's "is_receipt" value
 * @method float               getPostMoney()               Returns the current record's "post_money" value
 * @method timestamp           getCreatedAt()               Returns the current record's "created_at" value
 * @method timestamp           getUpdatedAt()               Returns the current record's "updated_at" value
 * @method Doctrine_Collection getClientBooksAdvertisment() Returns the current record's "ClientBooksAdvertisment" collection
 * @method Doctrine_Collection getOrderDetail()             Returns the current record's "OrderDetail" collection
 * @method Ordered             setOrdersId()                Sets the current record's "orders_id" value
 * @method Ordered             setGuyAddr()                 Sets the current record's "guy_addr" value
 * @method Ordered             setGuyPhone()                Sets the current record's "guy_phone" value
 * @method Ordered             setIsPaied()                 Sets the current record's "is_paied" value
 * @method Ordered             setGuyPayway()               Sets the current record's "guy_payway" value
 * @method Ordered             setPayStatus()               Sets the current record's "pay_status" value
 * @method Ordered             setIsDelivery()              Sets the current record's "is_delivery" value
 * @method Ordered             setIsReceipt()               Sets the current record's "is_receipt" value
 * @method Ordered             setPostMoney()               Sets the current record's "post_money" value
 * @method Ordered             setCreatedAt()               Sets the current record's "created_at" value
 * @method Ordered             setUpdatedAt()               Sets the current record's "updated_at" value
 * @method Ordered             setClientBooksAdvertisment() Sets the current record's "ClientBooksAdvertisment" collection
 * @method Ordered             setOrderDetail()             Sets the current record's "OrderDetail" collection
 * 
 * @package    BookCity
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOrdered extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ordered');
        $this->hasColumn('orders_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('guy_addr', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('guy_phone', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('is_paied', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('guy_payway', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('pay_status', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('is_delivery', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('is_receipt', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('post_money', 'float', 18, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 18,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('ClientBooksAdvertisment', array(
             'local' => 'orders_id',
             'foreign' => 'orders_id'));

        $this->hasMany('OrderDetail', array(
             'local' => 'orders_id',
             'foreign' => 'orders_id'));
    }
}