<?php

/**
 * AdvertismentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AdvertismentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AdvertismentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Advertisment');
    }
}