<?php

/**
 * BigBooksCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BigBooksCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BigBooksCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BigBooksCategory');
    }
}