<?php

/**
 * OrderedTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OrderedTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OrderedTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Ordered');
    }
}