<?php

/**
 * UserCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UserCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UserCategory');
    }
}