<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version15 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->dropForeignKey('client_books_advertisment', 'cuuu');
    }

    public function down()
    {
        $this->createForeignKey('client_books_advertisment', 'cuuu', array(
             'name' => 'cuuu',
             'local' => 'user_category_id',
             'foreign' => 'user_category_id',
             'foreignTable' => 'user_category',
             ));
    }
}