<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/06/20 16:50:53

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=BookCity',
  'username' => 'root',
  'password' => 220618,
  'name' => 'doctrine',
)),);
